apiVersion: v1
kind: Service
metadata:
  name: os-project-service
spec:
  ports:
  - port: 8888
    targetPort: 8888
    name: tcp
  selector:
    app: os-project
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: os-project-ingress
  annotations:
    kubernetes.io/ingress.class: “traefik”
spec:
  rules:
  - http:
    paths:
    - path: /
      backend:
        serviceName: os-project-service
        servicePort: 8888